<a href="https://colab.research.google.com/github/mossytreesandferns/DataCampDataEngineering/blob/master/IntrotoTensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Mount my drive- run the code, go to the link, accept.
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [2]:
#Change working directory to make it easier to access the files
import os
os.chdir("/content/gdrive/My Drive/Tensorflow/")
os.getcwd()

'/content/gdrive/My Drive/Tensorflow'

# Intro to Tensorflow

### Constants and Variables
constants - can't be changed <br>
tensors - variables <br>

In [0]:
import tensorflow as tf


# 0d tensor
d0 = tf.ones(1,)

# 1d tensor
d1 = tf.ones(2,)

# 2d tensor
d2 = tf.ones(2,3)

# 3d tensor
d3 = tf.ones(2,3,2)
d2, d3

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 1], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 1], dtype=int32)>)

In [0]:
from tensorflow import constant

# Constants are matrices made up of one number

a = constant(4, shape=[2,3])
b = constant(7, shape=[3,3,3])
c = constant([1,2,3,4], shape=[2,2]) # What's the unit in each spot in the matrix? why doesn't [2,2,2] work?

tf.zeros_like(input_tensor) - creates tensor of zeros shaped like input tensor <br>
tf.ones_like(input_tensor) - creates tensor of ones shaped like input tensor<br>
tf.fill()<br>

In [0]:
# Creating Variables formally

a = tf.Variable([1,2,3,4,5,6],dtype=tf.float32)
b = tf.Variable([1,2,3,4,5,6],dtype=tf.int16)

# Creating constant

c = tf.constant(2, tf.float32)

In [0]:
d1 = tf.multiply(a,c)
d2 = a*c # also okay

In [0]:
# not okay
d3 = b*c

InvalidArgumentError: ignored

Note that tensorflow version 2.0 allows you to use data as either a numpy array or a tensorflow constant object. Using a constant will ensure that any operations performed with that object are done in tensorflow.

In [0]:
# Import constant from TensorFlow
from tensorflow import constant

# Convert the credit_numpy array into a tensorflow constant
credit_constant = constant(credit_numpy) # credit_numpy is a 2d array-these can be pssed in as constants

# Print constant datatype
print('The datatype is:', credit_constant.dtype)

# Print constant shape
print('The shape is:', credit_constant.shape)

In [0]:
# Define the 1-dimensional variable A1
A1 = Variable([1, 2, 3, 4])

# Print the variable A1
print(A1)

# Convert A1 to a numpy array and assign it to B1
B1 = A1.numpy()

# Print B1
print(B1)

### Basic Operations

In [0]:
from tensorflow import constant, add

# tensors must have the same shape for addition 

# Define 0d tensors
t1 = tf.constant([4])
t2 = tf.constant([5])

# Define 1d tensors
t3 = tf.constant([1,2])
t4 = tf.constant([3,4])

# Define 2d tensors
t5 = tf.constant([[1,2],[3,4]])
t6 = tf.constant([[5,6],[7,8]])

A0 = add(t1, t2)
A1 = add(t3, t4)
A2 = add(t5, t6)

print(A0,A1,A2)

tf.Tensor([9], shape=(1,), dtype=int32) tf.Tensor([4 6], shape=(2,), dtype=int32) tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


In [0]:
# to multiply matrix of m x n, the next matrix has to be n x anything
# multiply() matrices have to be the same shape, matmul() matrices have to be mXn and nXanything

from tensorflow import constant, ones, matmul, multiply
A3 = multiply(t5,t6)
print(A3)

tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


In [0]:
from tensorflow import ones, reduce_sum

t = ones([2,3,4])

x = reduce_sum(t)
y = reduce_sum(t,0)
z = reduce_sum(t,1)
w = reduce_sum(t,2)
print(x,y,z,w)

tf.Tensor(24.0, shape=(), dtype=float32) tf.Tensor(
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]], shape=(3, 4), dtype=float32) tf.Tensor(
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]], shape=(2, 4), dtype=float32) tf.Tensor(
[[4. 4. 4.]
 [4. 4. 4.]], shape=(2, 3), dtype=float32)


In [0]:
reduce_sum(t,0).numpy() # adding numpy() prints out array() without extraneous info (?)

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]], dtype=float32)

In [0]:
# Define tensors A1 and A23 as constants
A1 = constant([1, 2, 3, 4])
A23 = constant([[1, 2, 3], [1, 6, 4]])

# Define B1 and B23 to have the correct shape
B1 = ones_like(A1)
B23 = ones_like(A23)

# Perform element-wise multiplication
C1 = multiply(A1, B1)
C23 = multiply(A23,B23)

# Print the tensors C1 and C23
print('C1: {}'.format(C1.numpy()))
print('C23: {}'.format(C23.numpy()))

In [0]:
# Define features, params, and bill as constants
features = constant([[2, 24], [2, 26], [2, 57], [1, 37]])
params = constant([[1000], [150]])
bill = constant([[3913], [2682], [8617], [64400]])

# Compute billpred using features and params
billpred = matmul(features,params)

# Compute and print the error
error = bill - billpred
print(error.numpy())

### Advanced Operations

gradient(), reshape(), and random()

In [0]:
# gradient()- computes slope of function at a point, finds min or max of a function (where slope is 0) to minimize or maximize a problem
# reshape()- reshapes a tensor
# random()- populates a tensor with entries from a probability distribution

In [0]:
import tensorflow as tf
# GradientTape() performs automatic differentiation

# Define x
x = tf.Variable(-1.0)

# Define y in an instance of GradientTape()
with tf.GradientTape() as tape:
  tape.watch(x)
  y = tf.multiply(x,x)  # This translates to y=x^2

# Evaluate gradient of y=x^2 at x=-1
g = tape.gradient(y,x)
print(g.numpy())  

-2.0


Images as tensors. Grayscale images of values between 0 and 255 (2d matrix of image pixels).  Image gets reshaped to m X 1 vector... (m X n X n X 1 --> m X 1)

In [0]:
import tensorflow as tf

# Generate grayscale image
im = tf.random.uniform([2,2],maxval=255,dtype='int32')
# Reshape grayscale image
im = tf.reshape(im,[2*2, 1]) # multiply all dimensions of original tensor together to get number of rows and make ti one column
im

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[ 33],
       [ 90],
       [ 76],
       [213]], dtype=int32)>

In [0]:
# Generate color image
color = tf.random.uniform([2,2,3], maxval=255, dtype='int32')
# Reshape color image
color = tf.reshape(color, [2*2,3]) # anomalous

In [0]:
# Reshape the grayscale image tensor into a vector
gray_vector = reshape(gray_tensor, (784, 1)) # multiply all dimensions of original tensor together to get number of rows and make ti one column

# Reshape the color image tensor into a vector
color_vector = reshape(color_tensor, (2352, 1))# multiply all dimensions of original tensor together to get number of rows and make ti one column

In [0]:
import tensorflow as tf
from tensorflow import GradientTape

def compute_gradient(x0):
  	# Define x as a variable with an initial value of x0
	x = tf.Variable(x0)
	with GradientTape() as tape:
		tape.watch(x)
        # Define y using the multiply operation
		y = multiply(x,x)
    # Return the gradient of y with respect to x
	return tape.gradient(y, x).numpy()

# Compute and print gradients at x = -1, 1, and 0
print(compute_gradient(-1.0))
print(compute_gradient(1.0))
print(compute_gradient(0.0))

-2.0
2.0
0.0


In [0]:
# Reshape model from a 1x3 to a 3x1 tensor
model = reshape(model, (1*3, 1))

# Multiply letter by model
output = matmul(letter, model)

# Sum over output and print prediction using the numpy method
prediction = reduce_sum(output)
print(prediction.numpy())

# Linear Models
### Input Data

In [0]:
import numpy as np
import pandas as pd
import tensorflow as tf

data = pd.read_csv('kc_house_data.csv')
data.head()

id             date     price  ...     long  sqft_living15  sqft_lot15
0  7129300520  20141013T000000  221900.0  ... -122.257           1340        5650
1  6414100192  20141209T000000  538000.0  ... -122.319           1690        7639
2  5631500400  20150225T000000  180000.0  ... -122.233           2720        8062
3  2487200875  20141209T000000  604000.0  ... -122.393           1360        5000
4  1954400510  20150218T000000  510000.0  ... -122.045           1800        7503

[5 rows x 21 columns]

In [0]:
data.shape

(21613, 21)

Using native numpy method

In [0]:
# Convert to numpy array
housing = np.array(data)

In [0]:
# Convert price columns
price = np.array(housing[:,2], dtype=np.float32) # had to change column name from label to numeric index

# Convert the waterfront column
waterfront = np.array(housing[:,8], dtype=np.bool) # had to change column name from label to numeric index
price, waterfront

(array([221900., 538000., 180000., ..., 402101., 400000., 325000.],
       dtype=float32), array([False, False, False, ..., False, False, False]))

Using a tensorflow method

In [0]:
housing = pd.read_csv('kc_house_data.csv')
price = tf.cast(housing['price'], tf.float32)
waterfront = tf.cast(housing['waterfront'], tf.bool)
price, waterfront

(<tf.Tensor: shape=(21613,), dtype=float32, numpy=
 array([221900., 538000., 180000., ..., 402101., 400000., 325000.],
       dtype=float32)>,
 <tf.Tensor: shape=(21613,), dtype=bool, numpy=array([False, False, False, ..., False, False, False])>)

### Loss Functions
<br>
Loss functions explain how well model fits data. Higher value --> worse fit.<br>
<br>
1. Mean squared error (MSE) - penalizes outlier, strong sensitivity near 0.<br>
2. Mean absolute error (MAE) - corresponds linearly with error, low sensitivity near 0. Minimize impact of outliers.<br>
3. Huber loss - like MSE near 0 and MEA beyond. Minimize impact of outliers.<br>
<br>
tf.keras.losses.mse(), tf.keras.losses.mae(), tf.keras.losses.Huber()

In [0]:
# Use two tensors, actual and predicted values
loss = tf.keras.losses.mse(actual, predicted) # returns average of squared difference 

In [0]:
# Define linear regression model
from tensorflow import keras

def linear_regression(intercept, slope=slope, features=features):
  return intercept + features*slope

def loss_function(intercept, slope, targets=targets, features=features): # Run twice: once with test data, once with default data
  predictions = linear_regression(intercept, slope)

  return tf.keras.losses.mse(targets, predictions)


### Linear Regression
<br>
In linear regression we plot data points to see the trend in the data to observe possible correlation between input and output variables.  Multivariate regressions are possible.
<br>
Transforming the data into a log of itself minimizes the impact of variability in data points and skewedness of data and converts it into a set that is closer to a normalized set of data points.
<br>


In [0]:
housing = pd.read_csv('kc_house_data.csv')
housing = np.array(data)

# Define targets and predictions
size = np.array(housing[:,5], dtype=np.float32)
price = np.array(housing[:,2], dtype=np.float32) 

# Define intercept and slope
intercept = tf.Variable(0.1, dtype=np.float32)
slope = tf.Variable(0.1, dtype=np.float32)

size, price

(array([1180., 2570.,  770., ..., 1020., 1600., 1020.], dtype=float32),
 array([221900., 538000., 180000., ..., 402101., 400000., 325000.],
       dtype=float32))

In [0]:
# Define a linear regression model
def linear_regression(intercept, slope, features=size):
  return intercept + slope*features

In [0]:
# Define loss function
def loss_function(intercept, slope, targets=price, features=size):
  predictions = linear_regression(intercept, slope)
  return tf.keras.losses.mse(targets, predictions)

In [0]:
# Define and optimization method
opt = tf.keras.optimizers.Adam()  # Optimization methods change the slope and intercept in directions that decreases the value of losses

In [0]:
# Utilizeing opt

for i in range(1000):
  opt.minimize(lambda: loss_function(intercept, slope), var_list=[intercept, slope])
  print(loss_function(intercept, slope).numpy()) # Values are supposed to fall from 10 to < 1... why is mine different?

420785060000.0
420782400000.0
420779720000.0
420776970000.0
420774250000.0
420771530000.0
420768780000.0
420766100000.0
420763470000.0
420760850000.0
420758100000.0
420755370000.0
420752620000.0
420749900000.0
420747300000.0
420744600000.0
420741900000.0
420739200000.0
420736500000.0
420733800000.0
420731060000.0
420728400000.0
420725750000.0
420722870000.0
420720280000.0
420717630000.0
420714870000.0
420712200000.0
420709470000.0
420706880000.0
420704100000.0
420701370000.0
420698720000.0
420695970000.0
420693300000.0
420690600000.0
420687900000.0
420685120000.0
420682500000.0
420679800000.0
420677120000.0
420674400000.0
420671650000.0
420669030000.0
420666280000.0
420663660000.0
420660870000.0
420658200000.0
420655500000.0
420652840000.0
420650160000.0
420647470000.0
420644700000.0
420642000000.0
420639300000.0
420636620000.0
420633940000.0
420631200000.0
420628530000.0
420625800000.0
420623120000.0
420620440000.0
420617750000.0
420615060000.0
420612340000.0
420609620000.0
4206069400

In [0]:
print(intercept.numpy(), slope.numpy())

1.0991884 1.0991763


In [0]:
# Initialize an adam optimizer
opt = keras.optimizers.Adam(0.5)

for j in range(100):
	# Apply minimize, pass the loss function, and supply the variables
	opt.minimize(lambda: loss_function(intercept, slope), var_list=[intercept, slope])

	# Print every 10th value of the loss
	if j % 10 == 0:
		print(loss_function(intercept, slope).numpy())

# Plot data and regression line
plot_results(intercept, slope)

Note that we've defined a vector of parameters, params, as a variable, rather than using three variables. Here, params[0] is the intercept and params[1] and params[2] are the slopes.

In [0]:
'''Linear regression using multiple inputs'''

# Define the linear regression model
def linear_regression(params, feature1 = size_log, feature2 = bedrooms):
	return params[0] + feature1*params[1] + feature2*params[2]

# Define the loss function
def loss_function(params, targets = price_log, feature1 = size_log, feature2 = bedrooms):
	# Set the predicted values
	predictions = linear_regression(params, feature1, feature2)
  
	# Use the mean absolute error loss
	return keras.losses.mae(targets, predictions)

# Define the optimize operation
opt = keras.optimizers.Adam()

# Perform minimization and print trainable variables
for j in range(10):
	opt.minimize(lambda: loss_function(params), var_list=[params])
	print_results(params)

### Batch Training
<br>
Use for large datasets where os/gpu can't handle chunks over a certain size.  Passes over chunks of data are called epochs.  Pandas and chunksize again.

In [0]:
import tensorflow as tf
import pandas as pd
import numpy as np

# Define intercept and slope
intercept = tf.Variable(0.1, dtype=np.float32)
slope = tf.Variable(0.1, dtype=np.float32)

# Define a linear regression model
def linear_regression(intercept, slope, features):
  return intercept + slope*features

# Define loss function
def loss_function(intercept, slope, targets, features):
  predictions = linear_regression(intercept, slope, features)
  return tf.keras.losses.mse(targets, predictions)

# Define and optimization method
opt = tf.keras.optimizers.Adam()

# for i in range(1000):
#   opt.minimize(lambda: loss_function(intercept, slope), var_list=[intercept, slope])
#   if j % 10 == 0:
# 		print(loss_function(intercept, slope).numpy())
  

# Load data in batches
for batch in pd.read_csv('kc_house_data.csv', chunksize=100):
  # Define targets and predictions
  size_batch = np.array(housing[:,5], dtype=np.float32)
  price_batch = np.array(housing[:,2], dtype=np.float32) 

  opt.minimize(lambda: loss_function(intercept, slope, price_batch, size_batch), var_list=[intercept, slope])

  print(intercept.numpy(), slope.numpy())  


0.101 0.101
0.102 0.102
0.103 0.103
0.103999995 0.103999995
0.10499999 0.10499999
0.10599999 0.10599999
0.106999986 0.106999986
0.10799998 0.10799998
0.108999975 0.108999975
0.10999997 0.10999997
0.110999964 0.110999964
0.11199996 0.11199996
0.11299995 0.11299995
0.11399995 0.11399995
0.11499994 0.11499994
0.11599994 0.11599994
0.11699993 0.11699993
0.11799992 0.11799992
0.118999906 0.118999906
0.11999989 0.11999989
0.12099988 0.12099988
0.12199987 0.12199987
0.122999854 0.122999854
0.123999834 0.123999834
0.124999814 0.124999814
0.1259998 0.1259998
0.12699977 0.12699977
0.12799974 0.12799974
0.12899971 0.12899971
0.12999968 0.12999968
0.13099965 0.13099965
0.13199963 0.13199963
0.1329996 0.1329996
0.13399957 0.13399957
0.13499954 0.13499954
0.1359995 0.1359995
0.13699946 0.13699946
0.13799942 0.13799942
0.13899937 0.13899937
0.13999933 0.13999933
0.14099929 0.14099929
0.14199924 0.14199924
0.1429992 0.1429992
0.14399916 0.14399916
0.1449991 0.14499912
0.14599904 0.14599906
0.14699899 

# Neural Layers

### Dense Layers
input layer (features) --> hidden dense layer(s) sum(features*weights)into activation function --> output layer (prediction)

In [0]:
'''Method that uses matrix multiplication (linear algebra)'''

import tensorflow as tf

# Define features(inputs)
features = tf.constant([1,35])

# Define weights
weights = tf.Variable([-.05],[-0.1])

# Define bias
bias = tf.Variable([0.5])

# Multiply inputs by weights
product = tf.matmul(features, weights)

# Define dense layer with activation function
dense = tf.keras.activations.sigmoid(product+bias)

In [0]:
'''Method that uses higher-level/complete inbuilts'''

# Define input layer
features = tf.constant(data, tf.float32)

# Define first dense layer
dense = tf.keras.layers.Dense(10, activation='sigmoid')(inputs) # bias included but not defined by user

# Define second and third layers
dense2 = tf.keras.layers.Dense(5,activation='sigmoid')(dense)
output = tf.keras.layers.Dense(1,activation='sigmoid')(dense2)

In [0]:
# Initialize bias1
bias1 = Variable(1.0)

# Initialize weights1 as 3x2 variable of ones
weights1 = Variable(ones((3, 2))) # why are there two sets of parentheses?

# Perform matrix multiplication of borrower_features and weights1
product1 = matmul(borrower_features,weights1)

# Apply sigmoid activation function to product1 + bias1
dense1 = keras.activations.Dense(product1 + bias)

# Print shape of dense1
print("\n dense1's output shape: {}".format(dense1.shape))

In [0]:
# From previous step
bias1 = Variable(1.0)
weights1 = Variable(ones((3, 2)))
product1 = matmul(borrower_features, weights1)
dense1 = keras.activations.sigmoid(product1 + bias1)

# Initialize bias2 and weights2
bias2 = Variable(1.0)
weights2 = Variable(ones((2,1)))

# Perform matrix multiplication of dense1 and weights2
product2 = matmul(dense1,weights2)

# Apply activation to product2 + bias2 and print the prediction
prediction = keras.activations.sigmoid(product2+bias2)
print('\n prediction: {}'.format(prediction.numpy()[0,0]))
print('\n actual: 1')

In [0]:
# Compute the product of borrower_features and weights1
products1 = matmul(borrower_features,weights1)

# Apply a sigmoid activation function to products1 + bias1
dense1 = keras.activations.sigmoid(products1+bias1)

# Print the shapes of borrower_features, weights1, bias1, and dense1
print('\n shape of borrower_features: ', borrower_features.shape)
print('\n shape of weights1: ', weights1.shape)
print('\n shape of bias1: ', bias1.shape)
print('\n shape of dense1: ', dense1.shape)

In [0]:

# Define the first dense layer
dense1 = keras.layers.Dense(7, activation='sigmoid')(borrower_features)

# Define a dense layer with 3 output nodes
dense2 = keras.layers.Dense(3,activation='sigmoid')(dense1)

# Define a dense layer with 1 output node
predictions = keras.layers.Dense(1,activation='sigmoid')(dense2)

# Print the shapes of dense1, dense2, and predictions
print('\n shape of dense1: ', dense1.shape)
print('\n shape of dense2: ', dense2.shape)
print('\n shape of predictions: ', predictions.shape)

### Activation functions
<br>
linear matrix multiplication (inputs x weights), non linear activation (shaping) function for first dense layer (eg sigmoid)
<br>
1. Sigmoid - binary classification function, hidden layers<br>
2. ReLu -  hidden layers, accepts max of value passed to it and 0<br>
3. Softmax - used in output layer in classification problems in multiclass classification problems.


In [0]:
import tensorflow as tf

# Define inputs
inputs = tf.constant(borrower_features, tf.float32)

# Define dense layer 1
dense = tf.keras.layers.Dense(16, activation='relu')(borrower_features)

# Define dense layer 2
dense2 = tf.keras.layers.Dense(8, activation='sigmoid')(dense) # note switch to sigmoid

# Define output
output = tf.keras.layers.Dense(4, activation='softmax')(dense2)

In [0]:
# Construct input layer from features
inputs = constant(bill_amounts, float32)

# Define first dense layer
dense1 = keras.layers.Dense(3, activation='relu')(inputs)

# Define second dense layer
dense2 = keras.layers.Dense(2, activation='relu')(dense1)

# Define output layer
outputs = keras.layers.Dense(1, activation='sigmoid')(dense1)

# Print error for first five examples
error = default[:5] - outputs.numpy()[:5]
print(error)

In [0]:
# Construct input layer from borrower features
inputs = constant(borrower_features, float32)

# Define first dense layer
dense1 = keras.layers.Dense(10, activation='sigmoid')(inputs)

# Define second dense layer
dense2 = keras.layers.Dense(8, activation='relu')(dense1)

# Define output layer
outputs = keras.layers.Dense(6, activation='softmax')(dense2)

# Print first five predictions
print(outputs.numpy()[:5])

### Optimizers
<br>
Gradient Descent <br>
Stochastic gradient descent is less likely to get stuck in local minimums.<br>
Pass in a learning rate between 0.5 and 0.001.  Higher learning rates can cause function overshoot global minimum. <br>
<br>
Root Mean Squared (RMS) optimizer<br>
Applies different learning rates to each feature.  <br>
Pass in learning rate, momentum and decay.  Setting the decay to a low value prevents momentum from building too much. <br>
<br>
Adaptive Moment (Adam) optimizer<br>
Generally a good first choice because it performs better with default parameter values.
Pass in learning rate and beta1. Lower beta1 to have momentum decay faster.

In [0]:
import tensorflow as tf

# Define model function
def model(bias, weights, features = borrower_features):
  product = tf.matmul(features, weights)
  return tf.keras.activations.sigmoid(product+bias)

# Define loss function, computes predicted values and loss
def loss_function(bias, weights, targets=default, features=borrower_features):
  predictions = model(bias, weights)
  return tf.keras.losses.binary_crossentropy(targets, predictions)  

# Minimize loss function
opt = tf.keras.optimizers.RMSprop(learning_rate=0.01,momentum=0.9)
opt.minimize(lambda: loss_function(bias, weights), var_list=[bias,weights])  


In [0]:
# Initialize x_1 and x_2
x_1 = Variable(6.0,float32)
x_2 = Variable(0.3,float32)

# Define the optimization operation
opt = keras.optimizers.SGD(learning_rate=0.01)

for j in range(100):
	# Perform minimization using the loss function and x_1
	opt.minimize(lambda: loss_function(x_1), var_list=[x_1])
	# Perform minimization using the loss function and x_2
	opt.minimize(lambda: loss_function(x_2), var_list=[x_2])

# Print x_1 and x_2 as numpy arrays
print(x_1.numpy(), x_2.numpy())

In [0]:

# Initialize x_1 and x_2
x_1 = Variable(0.05,float32)
x_2 = Variable(0.05,float32)

# Define the optimization operation for opt_1 and opt_2
opt_1 = keras.optimizers.RMSprop(learning_rate=0.01, momentum=0.99)
opt_2 = keras.optimizers.RMSprop(learning_rate=0.01, momentum=0.00)

for j in range(100):
	opt_1.minimize(lambda: loss_function(x_1), var_list=[x_1])
    # Define the minimization operation for opt_2
	opt_2.minimize(lambda: loss_function(x_2), var_list=[x_2])

# Print x_1 and x_2 as numpy arrays
print(x_1.numpy(), x_2.numpy())

### Training a Network in Tensorflow
<br>
Use random values taken from normal distributions to initialize varibles in large datasets: ones and doing it by hand wont work. Can also use Glorot initializers.

In [0]:
import tensorflow as tf

# Choosing random weights

# Define a 500x500 normal variable
weights = tf.Variable(tf.random.normal([500,500]))

# Define a truncated 500x500 random normal variable
weights = tf.Variable(tf.random.truncated_normal([500,500])) # gets rid of large and small numbers in set

In [0]:
# Define dense layer with default initializer
dense = tf.keras.layers.Dense(32, activation='relu')

# Define dense layer with zeros initializer
dense = tf.keras.layers.Dense(32, activation='relu', kernel_initializer='zeros')

#### Neural Networks and Overfitting: Apply dropout

In [0]:
import numpy as np
import tensorflow as tf


# Define input data, dense layers
inputs = np.array(borrower_features, float32)
dense = tf.keras.layers.Dense(32, activation='relu')(inputs)
dense2 = tf.keras.layers.Dense(16, activation='relu')(dense)

# Apply dropout operation
dropout = tf.keras.layers.dropout(0.25)(dense2)

# Create outputs
output = tf.keras.layers.Dense(1, activation='sigmoid')(dropout)

In [0]:
# Define the layer 1 weights
w1 = Variable(random.normal([23, 7]))

# Initialize the layer 1 bias
b1 = Variable(ones([7]))

# Define the layer 2 weights
w2 = Variable(random.normal([7,1]))

# Define the layer 2 bias
b2 = Variable([0.0])

In [0]:

# Define the model
def model(w1, b1, w2, b2, features = borrower_features):
	# Apply relu activation functions to layer 1
	layer1 = keras.activations.relu(matmul(features, w1) + b1)
    # Apply dropout
	dropout = keras.layers.Dropout(0.25)(layer1)
	return keras.activations.sigmoid(matmul(dropout, w2) + b2)

# Define the loss function
def loss_function(w1, b1, w2, b2, features = borrower_features, targets = default):
	predictions = model(w1, b1, w2, b2)
	# Pass targets and predictions to the cross entropy loss
	return keras.losses.binary_crossentropy(targets, predictions)

In [0]:

# Train the model
for j in range(100):
    # Complete the optimizer
	opt.minimize(lambda: loss_function(w1, b1, w2, b2), 
                 var_list=[w1, b1, w2, b2])

# Make predictions with model
model_predictions = model(w1, b1, w2, b2, test_features)

# Construct the confusion matrix
confusion_matrix(test_targets, model_predictions)

# High Level API's 

### Defining Neural Networks with Keras

The sequential API:

In [0]:
import tensorflow as tf
from tensorflow import keras

# Define model
model = keras.Sequential()

# Define first hidden layer
model.add(keras.layers.Dense(16, activation='relu', inputshape=(28*28,)))

# Define second hidden layer
model.add(keras.layers.Dense(8, activation='relu'))

# Define output layer
model.add(keras.layers.Dense(4, activation='softmax'))

#model.summary() # returns summary of model


In [0]:
# Compile the model
model.compile('adam', loss='categorical_crossentropy')

# Summarize the model
print(model.summary())

Using the functional api for training two models at once:

In [0]:
# Define model 1 input layer shape
model1_inputs = tf.keras.Input(shape=(28*28,))

# Define model 2 input layer shape
model2_inputs = tf.keras.Input(shape=(10,))



# Define layer 1 for model 1
model1_layer1 = tf.keras.layers.Dense(12, activation='relu')(model1_inputs)

# Define layer 2 for model 1
model1_layer2 = tf.keras.layers.Dense(4, activation='softmax')(model1_layer1)


# Define layer 1 for model 2
model2_layer1 = tf.keras.layers.Dense(8, activation='relu')(model2_inputs)

# Define layer 2 for model 1
model2_layer2 = tf.keras.layers.Dense(4, activation='softmax')(model2_layer1)

In [0]:
# Merge model 1 and model 2
merged = tf.keras.layers.add([model1_layer2, model2_layer2])

In [0]:
# Define a functional model
model = tf.keras.Model(inputs=[model1_layer2, model2_layer2], outputs=merged)

# Compile the model
model.compile('adam', loss='categorical_crossentropy')

print(model.summary())

In [0]:
# given

# Define a Keras sequential model
model = keras.Sequential()

# Define the first dense layer
model.add(keras.layers.Dense(16, activation='relu', input_shape=(784,)))

# Define the second dense layer
model.add(keras.layers.Dense(8, activation='relu'))

# Define the output layer
model.add(keras.layers.Dense(4, activation='softmax'))

# Print the model architecture
print(model.summary())

In [0]:
# given

# Define the first dense layer
model.add(keras.layers.Dense(16, activation='sigmoid', input_shape=(784,)))

# Apply dropout to the first layer's output
model.add(keras.layers.Dropout(0.25))

# Define the output layer
model.add(keras.layers.Dense(4, activation='softmax'))

# Compile the model
model.compile('adam', loss='categorical_crossentropy')

# Print a model summary
print(model.summary())

In [0]:

# For model 1, pass the input layer to layer 1 and layer 1 to layer 2
m1_layer1 = keras.layers.Dense(12, activation='sigmoid')(m1_inputs)
m1_layer2 = keras.layers.Dense(4, activation='softmax')(m1_layer1)

# For model 2, pass the input layer to layer 1 and layer 1 to layer 2
m2_layer1 = keras.layers.Dense(12, activation='relu')(m2_inputs)
m2_layer2 = keras.layers.Dense(4, activation='softmax')(m2_layer1)

# Merge model outputs and define a functional model
merged = keras.layers.add([m1_layer2, m2_layer2])
model = keras.Model(inputs=[m1_inputs, m2_inputs], outputs=merged)

# Print a model summary
print(model.summary())

### Training and Validation with Keras
<br>
Steps: load and clean data, define model, train and validate model, evaluate model

In [0]:
import tensorflow as tf
import numpy as np

# Define a sequential model
model = tf.keras.Sequential()

# Define hidden layer
model.add(tf.keras.layers.Dense(16, activation='relu', input_shape=(784,)))

# Define output layer
model.add(tf.keras.Dense(4, activation='softmax'))

# Compile
model.compile('adam', loss='categorical_crossentropy')

# Train model
model.fit(image_features, image_labels) # additional parameters include batchsize(32 by default) and epoch (# of times trained on the full set of batches)

In [0]:
# Training model with validation split, creates section of training set for validating
model.fit(features, labels, epochs=10, validation_split=0.20) # if training loss falls much below validation loss, 
# this indicates that the model is overfitting.  Either shorten training or add regularization(?) or dropout

In [0]:
# Add metrics= parameter to model.compile get percentage of accurately classified data points insted of 
model.compile('adam', loss='categorical_crossentropy', metrics=['accuracy'])
# Same .fit parameters
model.fit(features, labels, epochs=10, validation_split=0.20)

In [0]:
# Evaluate the test set
model.evaluate(test)  # When did we separate out the test set?

In [0]:
# Given

# Define a sequential model
model = keras.Sequential()

# Define a hidden layer
model.add(keras.layers.Dense(16, activation='relu', input_shape=(784,)))

# Define the output layer
model.add(keras.layers.Dense(4, activation='softmax'))

# Compile the model
model.compile('SGD', loss='categorical_crossentropy')

# Complete the fitting operation
model.fit(sign_language_features, sign_language_labels, epochs=5)

In [0]:
# Define sequential model
model = keras.Sequential()

# Define the first layer
model.add(keras.layers.Dense(32, activation='sigmoid', input_shape=(784,)))

# Add activation function to classifier
model.add(keras.layers.Dense(4, activation='softmax'))

# Set the optimizer, loss function, and metrics
model.compile(optimizer='RMSprop', loss='categorical_crossentropy', metrics=['accuracy'])

# Add the number of epochs and the validation split
model.fit(sign_language_features, sign_language_labels, epochs=10, validation_split=0.10)

In [0]:
# Define sequential model
model = keras.Sequential()

# Define the first layer
model.add(keras.layers.Dense(1024, activation='relu', input_shape=(784,)))

# Add activation function to classifier
model.add(keras.layers.Dense(4, activation='softmax'))

# Finish the model compilation
model.compile(optimizer=keras.optimizers.Adam(lr=0.01), 
              loss='categorical_crossentropy', metrics=['accuracy'])

# Complete the model fit operation
model.fit(sign_language_features, sign_language_labels, epochs=200, validation_split=0.50)

In [0]:
# Evaluate the small model using the train data
small_train = small_model.evaluate(train_features, train_labels)

# Evaluate the small model using the test data
small_test = small_model.evaluate(test_features, test_labels)

# Evaluate the large model using the train data
large_train = large_model.evaluate(train_features, train_labels)

# Evaluate the large model using the test data
large_test = large_model.evaluate(test_features, test_labels)

# Print losses
print('\n Small - Train: {}, Test: {}'.format(small_train, small_test))
print('Large - Train: {}, Test: {}'.format(large_train, large_test))

### Training Models with Estimators API
<br>
Order of Operations: define feature columns, load and transform data, define an estimator, apply train operation

In [0]:
# Defining a numeric feature column from kc housing set
size = tf.feature_colum.numeric_column('size')

# Define a categorical feature column
rooms = tf.feature_colum.categorical_column_with_vocabulary_list('rooms',['1','2','3','4','5'])

# Create feature list
features = [size, rooms]

# Define a matrix feature column (if using images)
features = [tf.feature_colum.numeric_column('image',shape=(784,))]

# Define input function
def input_fxn():
  # Define feature dictionary
  features = {'size':[1340, 1620, 1790],'rooms':[1,3,4]}
  # Define labels
  labels = [229000,538000,180000]
  return features, labels


In [0]:
# Define a deep neural network REGRESSION
model = tf.estimator.DNNRegressor(feature_colomns=features, hidden_units=[10,6,6,3]) # hidden units is number of nodes in each hidden layer

# Train the regression model
model.train(input_fxn, steps=20)

In [0]:
# Define a deep neural network CLASSIFICATION
model = tf.estimator.DNNClassifier(feature_columns=features, hidden_units=[32,16,8], n_classes=4)

# Train the classifier
model.train(input_fxn, steps=20)

#https://www.tensorflow.org/guides/estimators

In [0]:
'''How to pass in datafram colums to the input function'''

# Define feature columns for bedrooms and bathrooms
bedrooms = feature_column.numeric_column("bedrooms")
bathrooms = feature_column.numeric_column("bathrooms")

# Define the list of feature columns
feature_list = [bedrooms, bathrooms]

def input_fn():
	# Define the labels
	labels = np.array(housing['price'])
	# Define the features
	features = {'bedrooms':np.array(housing['bedrooms']), 
                'bathrooms':np.array(housing['bathrooms'])}
	return features, labels

In [0]:
# Define the model and set the number of steps
model = estimator.DNNRegressor(feature_columns=feature_list, hidden_units=[2,2])
model.train(input_fn, steps=1)

In [0]:
# Define the model and set the number of steps
model = estimator.LinearRegressor(feature_columns=feature_list)
model.train(input_fn, steps=2)

Checkout tensorflowhub (good for testing images on a model that has already been trained on a huge dataset) <br>
Tensorflow Probability (random number generators, optimizers for statistical models)