<a href="https://colab.research.google.com/github/mossytreesandferns/DataCampDataEngineering/blob/master/WritingEfficientCode.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Mount my drive- run the code, go to the link, accept.
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [76]:
#Change working directory to make it easier to access the files
import os
os.chdir("/content/gdrive/My Drive/DCCleaningData/")
os.getcwd()

'/content/gdrive/My Drive/DCCleaningData'

# Foundations for Efficiencies

### range(), list(), map(), enumerate()

In [0]:
# Use list comprehension when iterating over lists

In [4]:
nums = range(0,10)
numslist = list(nums)
numslist


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
evennums = range(0,20,2)
numslist = list(evennums)
numslist

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [6]:
# enumerate assigns numerical indexes to list items
l= ['a','x','d','f','p']
e = enumerate(l)
le = list(e)
le

[(0, 'a'), (1, 'x'), (2, 'd'), (3, 'f'), (4, 'p')]

In [7]:
# enumerate assigns numerical indexes to list items
l= ['a','x','d','f','p']
e = enumerate(l)
le = [*e]
le

[(0, 'a'), (1, 'x'), (2, 'd'), (3, 'f'), (4, 'p')]

In [8]:
l= ['a','x','d','f','p']
e = enumerate(l, start=5)
le = list(e)
le

[(5, 'a'), (6, 'x'), (7, 'd'), (8, 'f'), (9, 'p')]

In [9]:
floats = [1.1,2.2,3.3,4.4,5.5]
rounds = map(round,floats)
print(list(rounds))

[1, 2, 3, 4, 6]


In [10]:
floats = [1.1,2.2,3.3,4.4,5.5]
lam = map(lambda x: x**2, floats)
list(lam)

[1.2100000000000002,
 4.840000000000001,
 10.889999999999999,
 19.360000000000003,
 30.25]

In [11]:
names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']

# Rewrite the for loop to use enumerate
indexed_names = []
for i,name in enumerate(names):
    index_name = (i,name)
    indexed_names.append(index_name) 
print(indexed_names)

# Rewrite the above for loop using list comprehension
indexed_names_comp = [(i,name) for i,name in enumerate(names)]
print(indexed_names_comp)

# Unpack an enumerate object with a starting index of one
indexed_names_unpack = [*enumerate(names, start=1)]  # * makes it so that a list is printed without append, or list comprehension, [] == list()
print(indexed_names_unpack)


[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]
[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]
[(1, 'Jerry'), (2, 'Kramer'), (3, 'Elaine'), (4, 'George'), (5, 'Newman')]


In [12]:
names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']
# Use map to apply str.upper to each element in names
names_map  = map(lambda name:name.upper(), names)

# Print the type of the names_map
print(type(names_map))

# Unpack names_map into a list
names_uppercase =[*names_map]

# Print the list created above
print(names_uppercase)

<class 'map'>
['JERRY', 'KRAMER', 'ELAINE', 'GEORGE', 'NEWMAN']


### Numpy Arrays

In [13]:
import numpy as np
nums = np.array(range(5)) # all arrays have to have the same type
nums

array([0, 1, 2, 3, 4])

In [14]:
nums.dtype

dtype('int64')

In [15]:
nums = np.array([1,2.2, 5])
nums

array([1. , 2.2, 5. ])

In [16]:
# for loops or list comprehensions in addition to numpy arrays
nums = np.array([1,2.2, 5])
nums **2

array([ 1.  ,  4.84, 25.  ])

In [17]:
#words = np.array(['and','or','to'])

l = ([1,2,3],[4,5,6])
a = np.array(l)
l[0][2], a[0,2]



(3, 3)

In [18]:
[row[0] for row in l], a[:,0]

([1, 4], array([1, 4]))

In [19]:
# extracting data
l = [1,2,3,4,5,6]
a = np.array(l)
a[a>=3]
 # have to use for loop for l or list comprehension

array([3, 4, 5, 6])

In [20]:
b = [i for i in l  if i >= 3]
b

[3, 4, 5, 6]

In [21]:
# Create a list of arrival times
arrival_times = [*range(10, 60, 10)]

print(arrival_times)

# Convert arrival_times to an array and update the times
arrival_times_np = np.array(arrival_times)
new_times = arrival_times_np - 3

print(new_times)

# Use list comprehension and enumerate to pair guests to new times
guest_arrivals = [(names[name],time) for name,time in enumerate(new_times)]

print(guest_arrivals)

# # Map the welcome_guest function to each (guest,time) pair
# welcome_map = map(welcome_guest, guest_arrivals)

# guest_welcomes = [*welcome_map]
# print(*guest_welcomes, sep='\n')

[10, 20, 30, 40, 50]
[ 7 17 27 37 47]
[('Jerry', 7), ('Kramer', 17), ('Elaine', 27), ('George', 37), ('Newman', 47)]


# Timing and Profiling Code

### Examining Runtime

In [22]:
'''%timeit'''

# Create a list of arrival times
%timeit arrival_times = [*range(10, 60, 10)]

print(arrival_times)

# Convert arrival_times to an array and update the times
arrival_times_np = np.array(arrival_times)
new_times = arrival_times_np - 3

print(new_times)

# Use list comprehension and enumerate to pair guests to new times
%timeit guest_arrivals = [(names[name],time) for name,time in enumerate(new_times)] # names[name] points to digit created by enumerate, literal creation of tuple

print(guest_arrivals)

The slowest run took 8.21 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 298 ns per loop
[10, 20, 30, 40, 50]
[ 7 17 27 37 47]
The slowest run took 5.06 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.69 µs per loop
[('Jerry', 7), ('Kramer', 17), ('Elaine', 27), ('George', 37), ('Newman', 47)]


In [23]:
'''Timeit specifying iterations -r and loops -n'''

%timeit -r2 -n10 guest_arrivals = [(names[name],time) for name,time in enumerate(new_times)]

print(guest_arrivals)

10 loops, best of 2: 3.11 µs per loop
[('Jerry', 7), ('Kramer', 17), ('Elaine', 27), ('George', 37), ('Newman', 47)]


In [24]:
'''%%timeit on multiple lines of code'''

#%%timeit
# Create a list of arrival times
arrival_times = [*range(10, 60, 10)]

print(arrival_times)

# Convert arrival_times to an array and update the times
arrival_times_np = np.array(arrival_times)
new_times = arrival_times_np - 3

print(new_times)

# Use list comprehension and enumerate to pair guests to new times
guest_arrivals = [(names[name],time) for name,time in enumerate(new_times)]

print(guest_arrivals)

[10, 20, 30, 40, 50]
[ 7 17 27 37 47]
[('Jerry', 7), ('Kramer', 17), ('Elaine', 27), ('George', 37), ('Newman', 47)]


In [25]:
'''saving %timeit into a variable'''
import timeit
times = %timeit -o guest_arrivals = [(names[name],time) for name,time in enumerate(new_times)]


The slowest run took 6.36 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.73 µs per loop


In [26]:
times.timings # .timings deprecated?

AttributeError: ignored

In [27]:
times.best

1.7264986079999857e-06

In [28]:
times.worst

1.0982000020476335e-05

In [29]:
dicti = %timeit -o di = dict() # formal syntax

The slowest run took 14.25 times longer than the fastest. This could mean that an intermediate result is being cached.
10000000 loops, best of 3: 103 ns per loop


In [30]:
fdict = %timeit -o di = {} # literal syntax

10000000 loops, best of 3: 38.7 ns per loop


In [31]:
# Create a list of integers (0-50) using list comprehension
nums_list_comp = [num for num in range(51)]
print(nums_list_comp)


# Create a list of integers (0-50) by unpacking range
nums_unpack = [*range(51)]
print(nums_unpack)

%timeit nums_list_comp = [num for num in range(51)]
%timeit nums_unpack = [*range(51)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
1000000 loops, best of 3: 1.56 µs per loop
The slowest run took 4.87 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 569 ns per loop


In [32]:
# Create a list using the formal name
formal_list = list()
print(formal_list)

# Create a list using the literal syntax
literal_list = []
print(literal_list)

[]
[]


In [33]:
'''numpy arrays are faster''' 
%%timeit
... wts_np = np.array(wts)
... hero_wts_lbs_np = wts_np * 2.20462

%%timeit
... hero_wts_lbs = []
... for wt in wts:
...     hero_wts_lbs.append(wt * 2.20462)

SyntaxError: ignored

### Code Profiling for runtime

In [34]:
'''Runtime profiling on functions/multiple lines of code'''
# line_profiler package
!pip install line_profiler

     |████████████████████████████████| 71kB 1.8MB/s 


In [0]:
%load_ext line_profiler

In [0]:
#%lprun -f name_of_function name_of_function(parameters) #-f specifies that a function is being profiled

In [37]:
li1 = ['Oh','You\'re']
li2 = ['my!', 'kidding!']
def string_sentence(l1, l2):
  com = zip(l1, l2)
  l = [*com]
  return l
print(string_sentence(li1,li2))   
%lprun -f string_sentence string_sentence(li1,li2)

[('Oh', 'my!'), ("You're", 'kidding!')]


### Code Profiling for Memory Usage

In [0]:
'''Use sys for memory usage'''

import sys #sys.getsizeof() for object code usage

In [39]:
# for line by line usage, use memory_profiler

!pip install memory_profiler

  Created wheel for memory-profiler: filename=memory_profiler-0.57.0-cp36-none-any.whl size=28992 sha256=5b69e306a6327f5e4db60f8b3e9be6a4701efb0b8455e71c0d7b0e6d12c21386
  Stored in directory: /root/.cache/pip/wheels/74/20/b5/20964ef97be73d2c3a695c9cad7bccd96d1e3e737a8163861f
Successfully built memory-profiler


In [0]:
%load_ext memory_profiler


In [41]:
li1 = ['Oh','You\'re']
li2 = ['my!', 'kidding!']
def string_sentence(l1, l2):
  com = zip(l1, l2)
  l = [*com]
  return l
print(string_sentence(li1,li2))
%mprun -f string_sentence string_sentence(li1,li2) # can only be used on functions defined in physical files

[('Oh', 'my!'), ("You're", 'kidding!')]
ERROR: Could not find file <ipython-input-41-20745907e9f8>
NOTE: %mprun can only be used on functions defined in physical files, and not in the IPython environment.



In [0]:
# create .py file and drop into local directory


#### Bringing file into Colab 

In [0]:
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [0]:
module = drive.CreateFile({'id':'1psxvkic9wY6-4tAhtRTsFgWQvorLlpEn'})

In [0]:
module.GetContentFile('stringsentence.py')

In [45]:
from stringsentence import string_sentence
%mprun -f string_sentence string_sentence(li1,li2)

[('Oh', 'my!'), ("You're", 'kidding!')]



# Gaining Efficiencies

### Efficiently combining, counting, iterating

In [46]:
# Combining objects slow way 6 lines
names = ['John', 'Anne','Phyllis']
points = [45,26,78]

combined = []
for i, name in enumerate(names): # digit comes first, i, name in enumerate(names)
  combined.append((name, points[i]))

print(combined)  

[('John', 45), ('Anne', 26), ('Phyllis', 78)]


In [47]:
# Faster way is zip 2 lines
combined = zip(names, points)
print([*combined])

[('John', 45), ('Anne', 26), ('Phyllis', 78)]


In [48]:
'''Collections module'''
# specialized data types: namedtuple, deque, Counter, OrderedDict, defaultdict

# Creating dictionaries of counts: slow way

stuff_to_count=['and','and','and','and','or','or','or','ought','ought','ought','ought','ought']
di = {}

for i in stuff_to_count:
  if i in di:
    di[i] += 1
  else:
    di[i] = 1  

print(di)

{'and': 4, 'or': 3, 'ought': 5}


In [49]:
# Creating dictionaries of counts: Counter

from collections import Counter

stuff_to_count=['and','and','and','and','or','or','or','ought','ought','ought','ought','ought']

di = Counter(stuff_to_count)
di

Counter({'and': 4, 'or': 3, 'ought': 5})

In [50]:
# Combinatoric Generators: product, permutations,combinations
stuff_to_count=['and','and','and','and','or','or','or','ought','ought','ought','ought','ought']
combo = []
# slow way
for x in stuff_to_count:
  for y in stuff_to_count:
    if x == y:
      continue
    if ((x,y) not in combo) & ((y,x) not in combo):  
        combo.append((x,y))

combo       

[('and', 'or'), ('and', 'ought'), ('or', 'ought')]

In [51]:
# fast way
from itertools import combinations
combos = combinations(stuff_to_count,2)
[*combos]

[('and', 'and'),
 ('and', 'and'),
 ('and', 'and'),
 ('and', 'or'),
 ('and', 'or'),
 ('and', 'or'),
 ('and', 'ought'),
 ('and', 'ought'),
 ('and', 'ought'),
 ('and', 'ought'),
 ('and', 'ought'),
 ('and', 'and'),
 ('and', 'and'),
 ('and', 'or'),
 ('and', 'or'),
 ('and', 'or'),
 ('and', 'ought'),
 ('and', 'ought'),
 ('and', 'ought'),
 ('and', 'ought'),
 ('and', 'ought'),
 ('and', 'and'),
 ('and', 'or'),
 ('and', 'or'),
 ('and', 'or'),
 ('and', 'ought'),
 ('and', 'ought'),
 ('and', 'ought'),
 ('and', 'ought'),
 ('and', 'ought'),
 ('and', 'or'),
 ('and', 'or'),
 ('and', 'or'),
 ('and', 'ought'),
 ('and', 'ought'),
 ('and', 'ought'),
 ('and', 'ought'),
 ('and', 'ought'),
 ('or', 'or'),
 ('or', 'or'),
 ('or', 'ought'),
 ('or', 'ought'),
 ('or', 'ought'),
 ('or', 'ought'),
 ('or', 'ought'),
 ('or', 'or'),
 ('or', 'ought'),
 ('or', 'ought'),
 ('or', 'ought'),
 ('or', 'ought'),
 ('or', 'ought'),
 ('or', 'ought'),
 ('or', 'ought'),
 ('or', 'ought'),
 ('or', 'ought'),
 ('or', 'ought'),
 ('ought', 

In [52]:
from itertools import combinations
s = ['a','e','i','o','u']
combos = combinations(s,2)
[*combos]

[('a', 'e'),
 ('a', 'i'),
 ('a', 'o'),
 ('a', 'u'),
 ('e', 'i'),
 ('e', 'o'),
 ('e', 'u'),
 ('i', 'o'),
 ('i', 'u'),
 ('o', 'u')]

In [53]:
names = ['John', 'Anne','Phyllis']
points = [45,26,78]
names_type1 = [*zip(names, points)]

print(*names_type1[:5], sep='\n')

('John', 45)
('Anne', 26)
('Phyllis', 78)


In [54]:
names = ['John', 'Anne','Phyllis']
points = [45,26,78]
floats = [.1,.2,.3]
names_type1 = [*zip(names, points,floats)]
names_type1

[('John', 45, 0.1), ('Anne', 26, 0.2), ('Phyllis', 78, 0.3)]

In [55]:
names = ['John', 'Anne','Phyllis','Derek','Janie']
points = [45,26,78]
names_type1 = [*zip(names, points)]
names_type1

[('John', 45), ('Anne', 26), ('Phyllis', 78)]

In [56]:
names = ['John', 'Anne','Phyllis','Derek','Janie']
points = [45,26,78]
names_type1 = [*zip(names[:3], points[:2])]
names_type1

[('John', 45), ('Anne', 26)]

In [57]:
# Collect the count of primary types
type_count = Counter(floats)
print(type_count, '\n')

# Collect the count of generations
gen_count = Counter(points)
print(gen_count, '\n')

# Use list comprehension to get each Pokémon's starting letter

starting_letters = [string[0] for string in names]


# Collect the count of Pokémon for each starting_letter
starting_letters_count = Counter(starting_letters)
print(starting_letters_count)

Counter({0.1: 1, 0.2: 1, 0.3: 1}) 

Counter({45: 1, 26: 1, 78: 1}) 

Counter({'J': 2, 'A': 1, 'P': 1, 'D': 1})


In [58]:
from itertools import combinations as co
ltwo = co(names, 2)
unpack = [*ltwo]

lfour = [*co(names,4)]
unpack, lfour

([('John', 'Anne'),
  ('John', 'Phyllis'),
  ('John', 'Derek'),
  ('John', 'Janie'),
  ('Anne', 'Phyllis'),
  ('Anne', 'Derek'),
  ('Anne', 'Janie'),
  ('Phyllis', 'Derek'),
  ('Phyllis', 'Janie'),
  ('Derek', 'Janie')],
 [('John', 'Anne', 'Phyllis', 'Derek'),
  ('John', 'Anne', 'Phyllis', 'Janie'),
  ('John', 'Anne', 'Derek', 'Janie'),
  ('John', 'Phyllis', 'Derek', 'Janie'),
  ('Anne', 'Phyllis', 'Derek', 'Janie')])

### Set Theory

In [59]:
names = ['John', 'Anne','Phyllis','Derek','Janie']
names2 = ['Miranda','Fergus','Craig','Alison','Stephanie','Derek','Janie']

# slow way

in_both = []
for a in names:
  for b in names2:
    if a == b:
      in_both.append(a)
in_both      

['Derek', 'Janie']

In [60]:
# faster way

set_1 = set(names)
set_2 = set(names2)

set_1.intersection(set_2)

{'Derek', 'Janie'}

In [61]:
set_1.difference(set_2)

{'Anne', 'John', 'Phyllis'}

In [62]:
set_2.difference(set_1)

{'Alison', 'Craig', 'Fergus', 'Miranda', 'Stephanie'}

In [63]:
set_1.symmetric_difference(set_2) # symmetric_difference: the opposite of intersection

{'Alison',
 'Anne',
 'Craig',
 'Fergus',
 'John',
 'Miranda',
 'Phyllis',
 'Stephanie'}

In [64]:
set_1.union(set_2) # combines all unique values

{'Alison',
 'Anne',
 'Craig',
 'Derek',
 'Fergus',
 'Janie',
 'John',
 'Miranda',
 'Phyllis',
 'Stephanie'}

In [0]:
# checking if an itemis in a set is faster than list of tuple

In [66]:
# pulling sets out of group with repeats

#slow way
stuff_to_count=['and','and','and','and','or','or','or','ought','ought','ought','ought','ought']

l = []
for i in stuff_to_count:
  if i not in l:
    l.append(i)
l    

['and', 'or', 'ought']

In [67]:
# faster way

setof = set(stuff_to_count)
setof

{'and', 'or', 'ought'}

### Eliminating Loops

In [68]:
'''use inbuilt functions to speed up runtime'''

stats = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]

# using a loop
l = []
for row in stats:
  l.append(sum(row))
print(l)

# using list comprehension
l = [sum(row) for row in stats]
print(l)

# using map runction
l = [*map(sum,stats)]
print(l)

[15, 40, 65]
[15, 40, 65]
[15, 40, 65]


In [69]:
#Combinations loops and itertools
#loops
names = ['John', 'Anne','Phyllis','Derek','Janie']
combo = []
# slow way
for x in names:
  for y in names:
    if x == y:
      continue
    if ((x,y) not in combo) & ((y,x) not in combo):  
        combo.append((x,y)) 


# Combinations 
names = ['John', 'Anne','Phyllis','Derek','Janie']
n = combinations(names,2)
combo, [*n]

([('John', 'Anne'),
  ('John', 'Phyllis'),
  ('John', 'Derek'),
  ('John', 'Janie'),
  ('Anne', 'Phyllis'),
  ('Anne', 'Derek'),
  ('Anne', 'Janie'),
  ('Phyllis', 'Derek'),
  ('Phyllis', 'Janie'),
  ('Derek', 'Janie')],
 [('John', 'Anne'),
  ('John', 'Phyllis'),
  ('John', 'Derek'),
  ('John', 'Janie'),
  ('Anne', 'Phyllis'),
  ('Anne', 'Derek'),
  ('Anne', 'Janie'),
  ('Phyllis', 'Derek'),
  ('Phyllis', 'Janie'),
  ('Derek', 'Janie')])

In [70]:
# USE NUMPY!!!
import numpy as np

stats = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

#loop way
l = []
for row in stats:
  avg = row.mean()
  l.append(avg)
print(l)

# numpy way
avgs = stats.mean(axis=1)
print(avgs)


[3.0, 8.0, 13.0]
[ 3.  8. 13.]


In [71]:
# Collect Pokémon that belong to generation 1 or generation 2
gen1_gen2_pokemon = [name for name,gen in zip(poke_names, poke_gens) if gen < 3]

# Create a map object that stores the name lengths
name_lengths_map = map(len, poke_names)

# Combine gen1_gen2_pokemon and name_lengths_map into a list
gen1_gen2_name_lengths = [*(gen1_gen2_pokemon, name_lengths_map)]

print(gen1_gen2_name_lengths_loop[:5])
print(gen1_gen2_name_lengths[:5])

NameError: ignored

In [0]:

# Create a total stats array
total_stats_np = stats.sum(axis=1)

# Create an average stats array
avg_stats_np = stats.mean(axis=1)

# Combine names, total_stats_np, and avg_stats_np into a list
poke_list_np = [*zip(names, total_stats_np, avg_stats_np)]

print(poke_list_np == poke_list, '\n')
print(poke_list_np[:3])
print(poke_list[:3], '\n')
top_3 = sorted(poke_list_np, key=lambda x: x[1], reverse=True)[:3]
print('3 strongest Pokémon:\n{}'.format(top_3))

### Writing Better Loops

In [72]:
# calculations or actions that are only done once (value doesn't change), pull out of loop to above, data conversions can often be done first or
# afterwards, 

names = ['John', 'Anne','Phyllis','Derek','Janie']
stats = np.array([5,6,7,8,9])

#Calculate mean first, not inside loop
stats_m = stats.mean()
for name, stat in zip(names,stats):
  # stats = np.array([5,6,7,8,9]) bad here
  if stat > stats_m:
    print(name,stat)



Derek 8
Janie 9


In [73]:
names = ['John', 'Anne','Phyllis','Derek','Janie']
stats = [5,6,7,8,9]
floats = [.1,.2,.3,.4,.5]

#bad way
l= []
for tup in zip(names,stats,floats):
  tup_list = list(tup)
  l.append(tup_list)
print(l)

# better way
m =[]
for tup in zip(names,stats,floats):
  m.append(tup)

n = [*map(list,m)] 
n 

[['John', 5, 0.1], ['Anne', 6, 0.2], ['Phyllis', 7, 0.3], ['Derek', 8, 0.4], ['Janie', 9, 0.5]]


[['John', 5, 0.1],
 ['Anne', 6, 0.2],
 ['Phyllis', 7, 0.3],
 ['Derek', 8, 0.4],
 ['Janie', 9, 0.5]]

In [0]:

# Collect all possible pairs using combinations()
possible_pairs = [*combinations(pokemon_types, 2)]

# Create an empty list called enumerated_tuples
enumerated_tuples = []

# Add a line to append each enumerated_pair_tuple to the empty list above
for i,pair in enumerate(possible_pairs, 1):
    enumerated_pair_tuple = (i,) + pair
    enumerated_tuples.append(enumerated_pair_tuple)

# Convert all tuples in enumerated_tuples to a list
enumerated_pairs = [*map(list, enumerated_tuples)]
print(enumerated_pairs)

In [0]:

# Calculate the total HP avg and total HP standard deviation
hp_avg = hps.mean()
hp_std = hps.std()

# Use NumPy to eliminate the previous for loop
z_scores = (hps - hp_avg)/hp_std

# Combine names, hps, and z_scores
poke_zscores2 = [*zip(names, hps, z_scores)]
print(*poke_zscores2[:3], sep='\n')

highest_hp_pokemon2 = [(name, hp, zscore) for name,hp,zscore in poke_zscores2 if zscore > 2]
print(*highest_hp_pokemon2, sep='\n')

# Basic Pandas Optimizations

### Intro to Pandas Dataframe Iteration

In [84]:
import pandas as pd
import numpy as np
tips = pd.read_csv('tips.csv')
tips.head(3)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3

In [86]:
# Slow way: What percent of the total bill was the tip?

# Create function to pass in the iteration
def calc_percent(tip, total):

  percent_tip = tip/total
  return np.round(percent_tip,2)

# Create iterative loop
percent_tips_list = []

for i in range(len(tips)): #specifying height of dataframe

  row = tips.iloc[i]
  total_bill = row['total_bill']
  tip = row['tip']
  tip_percent = calc_percent(tip, total_bill)
  percent_tips_list.append(tip_percent)

tips['percent_tip'] = percent_tips_list
tips.head(3)

total_bill   tip     sex smoker  day    time  size  percent_tip
0       16.99  1.01  Female     No  Sun  Dinner     2         0.06
1       10.34  1.66    Male     No  Sun  Dinner     3         0.16
2       21.01  3.50    Male     No  Sun  Dinner     3         0.17

In [89]:
# Faster way: What percent of the total bill was the tip? (similar lines but more efficient)
tips = pd.read_csv('tips.csv')

# Create function to pass in the iteration
def calc_percent(tip, total):

  percent_tip = tip/total
  return np.round(percent_tip,2)

# Use .iterrows()
percent_tips_list = []
for i, row in tips.iterrows(): # recall iterrows() returns a tuple of an index and a value, can also use one variable to store tuple
  
  tip = row['tip']
  total_bill = row['total_bill']
  tip_percent = calc_percent(tip, total_bill)
  percent_tips_list.append(tip_percent)

tips['percent_tip'] = percent_tips_list
tips.head(3)

total_bill   tip     sex smoker  day    time  size  percent_tip
0       16.99  1.01  Female     No  Sun  Dinner     2         0.06
1       10.34  1.66    Male     No  Sun  Dinner     3         0.16
2       21.01  3.50    Male     No  Sun  Dinner     3         0.17

### Another iterator method: itertuples():

In [90]:
# Faster than iterrows(), itertuples().  Have to use dot notation when accessing attributes (columns)
tips = pd.read_csv('tips.csv')

# Create function to pass in the iteration
def calc_percent(tip, total):

  percent_tip = tip/total
  return np.round(percent_tip,2)

# Use .iterrows()
percent_tips_list = []
for row in tips.itertuples(): # recall iterrows() returns a tuple of an index and a value, can also use one variable to store tuple
  
  tip = row.tip
  total_bill = row.total_bill
  tip_percent = calc_percent(tip, total_bill)
  percent_tips_list.append(tip_percent)

tips['percent_tip'] = percent_tips_list
tips.head(3)


total_bill   tip     sex smoker  day    time  size  percent_tip
0       16.99  1.01  Female     No  Sun  Dinner     2         0.06
1       10.34  1.66    Male     No  Sun  Dinner     3         0.16
2       21.01  3.50    Male     No  Sun  Dinner     3         0.17

In [97]:
for row in tips.itertuples():
  print(row)

Pandas(Index=0, total_bill=16.99, tip=1.01, sex='Female', smoker='No', day='Sun', time='Dinner', size=2, percent_tip=0.06)
Pandas(Index=1, total_bill=10.34, tip=1.66, sex='Male', smoker='No', day='Sun', time='Dinner', size=3, percent_tip=0.16)
Pandas(Index=2, total_bill=21.01, tip=3.5, sex='Male', smoker='No', day='Sun', time='Dinner', size=3, percent_tip=0.17)
Pandas(Index=3, total_bill=23.68, tip=3.31, sex='Male', smoker='No', day='Sun', time='Dinner', size=2, percent_tip=0.14)
Pandas(Index=4, total_bill=24.59, tip=3.61, sex='Female', smoker='No', day='Sun', time='Dinner', size=4, percent_tip=0.15)
Pandas(Index=5, total_bill=25.29, tip=4.71, sex='Male', smoker='No', day='Sun', time='Dinner', size=4, percent_tip=0.19)
Pandas(Index=6, total_bill=8.77, tip=2.0, sex='Male', smoker='No', day='Sun', time='Dinner', size=2, percent_tip=0.23)
Pandas(Index=7, total_bill=26.88, tip=3.12, sex='Male', smoker='No', day='Sun', time='Dinner', size=4, percent_tip=0.12)
Pandas(Index=8, total_bill=15.0

In [0]:
# for row in tips.itertuples():
#   print(row.tip)


### Pandas alternative to looping

In [103]:
# Even faster: .apply()
tips = pd.read_csv('tips.csv')

def calc_percent(tip, total):

  percent_tip = tip/total
  return np.round(percent_tip,2)

tips_apply = tips.apply(lambda row: calc_percent(row['tip'], row['total_bill']), axis=1)  # .apply() know it will act on a series, either axis=0 or axis=1
tips['percent_tip'] = tips_apply
tips.head(3)

total_bill   tip     sex smoker  day    time  size  percent_tip
0       16.99  1.01  Female     No  Sun  Dinner     2         0.06
1       10.34  1.66    Male     No  Sun  Dinner     3         0.16
2       21.01  3.50    Male     No  Sun  Dinner     3         0.17

In [107]:
numcolumns = tips[['total_bill','tip','size','percent_tip']]
rowwise = numcolumns.apply(sum, axis=0)
rowwise

total_bill     4827.77
tip             731.58
size            627.00
percent_tip      39.27
dtype: float64

In [108]:
columnwise= numcolumns.apply(sum, axis=1)
columnwise

0      20.06
1      15.16
2      27.68
3      29.13
4      32.35
       ...  
239    38.15
240    31.25
241    26.76
242    21.67
243    23.94
Length: 244, dtype: float64

In [109]:
def convert_str(value):
  if value == 'Yes':
    return 1
  else:
    return 0  

smoking = tips.apply(lambda row: convert_str(row['smoker']), axis=1)
smoking    

0      0
1      0
2      0
3      0
4      0
      ..
239    0
240    1
241    1
242    0
243    0
Length: 244, dtype: int64

In [111]:
def each_pay(total_bill, party_no):
  split_amt = total_bill/party_no
  amt = round(split_amt,2)
  return amt 

tips['split'] = tips.apply(lambda row: each_pay(row['total_bill'], row['size']), axis=1)
tips.head(3)  

total_bill   tip     sex smoker  day    time  size  percent_tip  split
0       16.99  1.01  Female     No  Sun  Dinner     2         0.06   8.49
1       10.34  1.66    Male     No  Sun  Dinner     3         0.16   3.45
2       21.01  3.50    Male     No  Sun  Dinner     3         0.17   7.00

### Optimal Pandas iterating

In [116]:
# Pandas internals: Avoid loops!!! Utilize Numpy broadcasting Characteristics!

tips['tip'].values[:10],type(tips['tip'].values)

(array([1.01, 1.66, 3.5 , 3.31, 3.61, 4.71, 2.  , 3.12, 1.96, 3.23]),
 numpy.ndarray)

In [122]:
#%timeit 
tips['tip_percent_again']=round(tips['tip']/tips['total_bill'],2) # Next fastest approach 372 µs per loop
#tips.head(3) 

The slowest run took 13.44 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 3: 372 µs per loop


In [123]:

%timeit tips['tips_per_III']=tips['tip'].values/tips['total_bill'].values # Fastest approach  108 µs per loop
#tips.head(3)

The slowest run took 5.86 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 108 µs per loop
